### ISSUE TITLE
Add sub task

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/List#1]
We need to have subtasks too to complete a task. Please consider adding sub-task to each task.

ex:

- Get Groceries 

- [ ] 1. Tomato from open market
- [ ] 2. Cheese from super market
- [ ] 3. Milk from neightborhood shop
- [ ] 4. Carrots from auntie's farm
- [ ] 5. etc..

- Study Python

1. Learn from youtube site
2. Visit this website
3. Read about arrays
4. Understand dictionaries.

**Comment by mrvladus** [comment]
I'm working on that!
