### ISSUE TITLE
Move sub-task from Task1 to Task2 (drag & drop) or with menu->move to->list of task

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/List#11]
Say we have 2 tasks:

1. Shopping
2. Medicines
  - Buy Chocolates

Say we mistakenly created a sub task "Buy chocolates" in Medicines, to fix, that as:

1. Shopping
    - Buy Chocolates
3. Medicines

Either we need drag and drag support or from 3 dots menu -> move to [Task lists]

**Comment by mrvladus** [comment]
Merged with #10
