### ISSUE TITLE
Apostrophe character displayed as character entity

### ISSUE THREAD

**Issue by CastelJeremy** [mrvladus/List#12]
If a task or sub-task title includes the apostrophe `'` character, it will be displayed as `&apos;` after the app is restarted.
If the title also includes the `&` character, the apostrophe is correctly displayed.

## Steps to reproduce

 - Launch the app
 - Create a task or a sub-task containing an apostrophe `'`
 - Restart the application

![image](https://github.com/mrvladus/List/assets/39135270/9e4e9834-edfa-4628-86c8-5b2a33b07fa6)

**Comment by CastelJeremy** [comment]
Also, if the sub-task is marked as done before closing the app, the apostrophe is correctly displayed.

**Comment by mrvladus** [comment]
Thanks! That is the problem with markup format. Fixed in [44.4.3](https://github.com/mrvladus/List/releases/tag/v44.4.3) now. You might need to remove old tasks and add them again. In 44.5 I'm gonna rewrite this system to avoid this sort of bugs in the future.

**Comment by CastelJeremy** [comment]
Awesome ! Thank you for the speedy update !
