### ISSUE TITLE
undo - redo support

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/List#14]
Required when we accidentally delete a task or sub-task, and want to undo.

Thanks.

**Comment by amka** [comment]
Good idea! I think it can be implemented like this:
- set some flag to indicate that the task is queued for deletion
- display popup notification with action to restore "deleted" task
- after some time, run a task to clear all tasks marked as "for deletion" and being in this state for some time, say, 2 minutes.
- marked tasks are not displayed in the application.

**Comment by fastrizwaan** [comment]
or simply, when clicked deleted, hide the task or sub-task and show in deleted tasks section, then unhide when restored is clicked from the deleted task section..

**Comment by mrvladus** [comment]
I planned to do this like in Nautilus file manager, when you delete files. When you delete task, Toast on the bottom appears with label "TASK_TEXT deleted" and button to Undo for about 10 seconds.

**Comment by fastrizwaan** [comment]
Toast is a good idea, but what happens after the user want to restore after 10 seconds? 

A trash like feature could handle undo/redo, irrespective of time.
