### ISSUE TITLE
Backup task list.

### ISSUE THREAD

**Issue by Base-115** [mrvladus/List#20]
Hi there.

I don't know this is the correct place to ask this...

Is possible backup the task list of List? I am the famous "newbie" in Linux and if this possible, can you explain to a stupid like me how exactly do this?

I am in Kubuntu 22.04 .

**Comment by mrvladus** [comment]
Hi! You can copy this file at ~/.var/app/io.github.mrvladus.List/data/data.json.
For example run this command to copy data file to your home folder:
```bash
cp ~/.var/app/io.github.mrvladus.List/data/data.json ~/data_backup.json
```

**Comment by mrvladus** [comment]
I'm gonna add button in the settings page to backup user data for situations like this.

**Comment by mrvladus** [comment]
Added button for backup in [44.6.2](https://github.com/mrvladus/List/releases/tag/44.6.2)

**Comment by Base-115** [comment]
Woo, awesome. Thank you to quick reply and the new feature to backup. ❤️
