### ISSUE TITLE
App Doesn't Fit On Mobile Devices

### ISSUE THREAD

**Issue by gondolyr** [mrvladus/List#24]
* Version: 44.6.4 (Flatpak)
* Operating System: PureOS (Debian-based)
* Severity: Minor annoyance

The app doesn't fit on a Librem 5 without turning on scaling from the phosh-mobile-settings app. The problem with turning on scaling is that the inputs, buttons, and text become small and difficult to read and tap. I expect the app to adapt to the screen like some other GNOME apps like Flatseal shown below with the screenshots.

There seems to be a minimum width set for the app that is preventing the app from resizing to 360px wide, even on the desktop.

Screenshots:

<details>
<summary>List - Scaling Off</summary>

![scaling_off](https://github.com/mrvladus/List/assets/57526088/1521b814-492b-4008-83df-6977ea4ba558)
</details>

<details>
<summary>List - Scaling On</summary>

![scaling_on](https://github.com/mrvladus/List/assets/57526088/b7ebb78e-ee89-4736-bfed-81fd549f596b)
</details>

<details>
<summary>Flatseal Example</summary>

![flatseal](https://github.com/mrvladus/List/assets/57526088/f4c4e6ba-6580-4e5c-8b16-8a46e20e9740)
</details>

**Comment by mrvladus** [comment]
Yes, width is fixed at 500px. I will fix this today. Thank you for report!

**Comment by mrvladus** [comment]
I've pushed new update on Flathub. Please comment here when you receive it!

**Comment by gondolyr** [comment]
> I've pushed new update on Flathub. Please comment here when you receive it!

It looks good now.

<details>
<summary>44.6.5 screenshot</summary>

![list_44 6 5](https://github.com/mrvladus/List/assets/57526088/37c937f3-70eb-4c95-8a50-0aef560b5d37)
</details>

**Comment by mrvladus** [comment]
Nice!
