### ISSUE TITLE
Can't translate your app!

### ISSUE THREAD

**Issue by vvvvvvitor** [mrvladus/List#28]
I've just finished translating your app to portuguese (Brazil), but for some reason the translation doesn't appear on the app.

![image](https://github.com/mrvladus/List/assets/119557151/d159556b-5175-41af-93f4-777dbfe71e68)

![image](https://github.com/mrvladus/List/assets/119557151/1747836f-ddad-425d-bb6d-30f13ce44a9f)

![image](https://github.com/mrvladus/List/assets/119557151/092697a3-6f7e-4251-8f87-3c7971328c2e)

**Comment by mrvladus** [comment]
Can you try launch it with this command:
```
LANGUAGE=pt_BR flatpak run io.github.mrvladus.List
```

**Comment by vvvvvvitor** [comment]
> Can you try launch it with this command:
> 
> ```
> LANGUAGE=pt_BR flatpak run io.github.mrvladus.List
> ```

Didn't work.

**Comment by mrvladus** [comment]
What is the output of `locale` command?

**Comment by vvvvvvitor** [comment]
> What is the output of `locale` command?

```
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=
```

**Comment by mrvladus** [comment]
Can you try this:
```
LANG=pt_BR flatpak run io.github.mrvladus.List
```

**Comment by vvvvvvitor** [comment]
> Can you try this:
> 
> ```
> LANG=pt_BR flatpak run io.github.mrvladus.List
> ```

Still in english.

**Comment by mrvladus** [comment]
Is there any errors in the terminal when you run it as
```
flatpak run io.github.mrvladus.List
```
?

**Comment by mrvladus** [comment]
Please open pull request against pt-translation branch

**Comment by vvvvvvitor** [comment]
> Is there any errors in the terminal when you run it as
> 
> ```
> flatpak run io.github.mrvladus.List
> ```
> 
> ?

Nope.

**Comment by vvvvvvitor** [comment]
> Please open pull request against pt-translation branch

Done!

**Comment by mrvladus** [comment]
Thank you! And what distro are you using?

**Comment by vvvvvvitor** [comment]
> Thank you! And what distro are you using?

Fedora 38

**Comment by mrvladus** [comment]
There was some changes in translations, I'll fix them and push to main branch with your translation included
