### ISSUE TITLE
Clear task button shouldn’t be red

### ISSUE THREAD

**Issue by bragefuglseth** [mrvladus/List#3]
Even though removing a task is a destructive action, using .destructive-action for every single instance of the remove button is unnecessarily distracting. The action also loses weight when *every* button is red anyways.

I suggest using a plain close icon (X) without any additional styling.

**Comment by mrvladus** [comment]
Good point! Fixed in [44.2.1](https://github.com/mrvladus/List/releases/tag/v44.2.1). Thanks for your feedback!
