### ISSUE TITLE
Sub-Task Checkbox

### ISSUE THREAD

**Issue by CastelJeremy** [mrvladus/List#5]
# Sub-Task Checkbox

Hello,
Would it be possible to add a checkbox or an option in the menu to mark a sub-task as done / undone ?

The sub-task could then be stylized with a strike-through and be deleted later-on.

**Comment by mrvladus** [comment]
Yes, I will add this functionality in the next release!

**Comment by mrvladus** [comment]
Added in [44.4](https://github.com/mrvladus/List/releases/tag/v44.4)
