### ISSUE TITLE
Maximized window issues: tasks not visible

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/List#6]
1. Only vertical arrangement of task does not look good when we maximize the window. Tiling the tasks would look better on a maximized or big window

![image](https://user-images.githubusercontent.com/1161682/236658866-a34e360a-524a-4fb7-ad54-457ad55b6fca.png)

This is small window: (looks ok)
![image](https://user-images.githubusercontent.com/1161682/236658831-d79c6d55-1bed-43c7-9f35-13910810c4c8.png)

**Comment by mrvladus** [comment]
I made tasks wider in [44.5](https://github.com/mrvladus/List/releases/tag/v44.5) so it looks better maximized. Tiling gonna add too much complexity, I want to keep application simple as a continuous sheet of paper and not over-complicate things.
