### ISSUE TITLE
show statistics about total tasks (open and completed)  and sub tasks

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/List#8]
![image](https://user-images.githubusercontent.com/1161682/236659147-dc056725-4528-4cdb-a14b-a5d9c9a12064.png)

In the main window, it should show, "Total tasks", "Open" and "Completed" 

and for each task, we should show completed/incomplete sub-tasks.

e.g., the task dropdown should show
[ Task 1 - 2/5 completed ]
- [  ] sub task 1
- [x] sub task 2
- [  ] sub task 3
- [x] sub task 4
- [x] sub task 5

Thanks

**Comment by mrvladus** [comment]
Added stats of sub-tasks in [44.5](https://github.com/mrvladus/List/releases/tag/v44.5). Task stats is not really needed. Maybe in the future. But for now I'm not really see the point. Thank you!
