### ISSUE TITLE
Make URL's clickable

### ISSUE THREAD

**Issue by fastrizwaan** [mrvladus/List#9]
We need websites these days for basic things:

[Task] Learn English: 
- [ ] visit https://www.youtube.com/watch?v=16TRYgboJsA&ab_channel=TheUrbanFight 
- [ ] check https://www.youtube.com/watch?v=ja2Sc8Tpfxo&ab_channel=LearnEnglish%7CLet%27sTalk-FreeEnglishLessons
- [ ] download https://drive.google.com/file/d/14YsW7xsCUhVq7igqFPKJCAWjr0ZD1Smq/view?usp=sharing

The above URLs are not clickable and there's the bug with urls, e.g.,

1st and 2nd youtube url are not shown at all incluing the `text` visit and `check` in the sub task, please add these to your sub task to see the bug:

`visit https://www.youtube.com/watch?v=16TRYgboJsA&ab_channel=TheUrbanFight` and 
`check https://www.youtube.com/watch?v=ja2Sc8Tpfxo&ab_channel=LearnEnglish%7CLet%27sTalk-FreeEnglishLessons`

![image](https://user-images.githubusercontent.com/1161682/236659688-8a3fbbfc-5048-4599-9c81-367d9d195c2b.png)

thanks

**Comment by mrvladus** [comment]
Bug is fixed in [44.4.1](https://github.com/mrvladus/List/releases/tag/v44.4.1)

**Comment by mrvladus** [comment]
Added in [44.5](https://github.com/mrvladus/List/releases/tag/v44.5).
